import "./globals.css";
import Script from "next/script";
import { Providers } from "../redux/Providers.jsx";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css" integrity="sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        </head>
      <body>
        
        <Providers>{children}</Providers>
        <ToastContainer/>
         <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="afterInteractive" 
        />
      </body>
    </html>
  );
}
